

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 0.85

[general]
#[colors.bright]
#black = "#545454"
#blue = "#94bff3"
#cyan = "#93e0e3"
#green = "#8ae234"
#magenta = "#b294bb"
#red = "#fc5454"
#white = "#ffffff"
#yellow = "#fce94f"

#[colors.normal]
#lack = "#3f3f3f"
#blue = "#94bff3"
#cyan = "#06989a"
#green = "#4e9a06"
#magenta = "#85678f"
#red = "#cc0000"
#white = "#dcdccc"
#yellow = "#c4a000"
#
#[colors.primary]
#background = "#222222"
#foreground = "#F9F9F9"


import = [
	"~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[terminal]
## BEGIN WAL
#[colors.primary]
#background = '#0f1016'
#foreground = '#8f8f99'
#
#[colors.cursor]
#text   = '#0f1016' # Apply background color to color of text inside cursor
#cursor = '#8f8f99' # Apply foreground color to color of cursor
#
#[colors.vi_mode_cursor]
#text    = '#0f1016' # Same as above
#cursor  = '#8f8f99'
#
#[colors.search.matches]
#foreground = '#0f1016' # Same as above
#background = '#c3c3c4' # Apply bright/white color to bg color of matching search
#
#[colors.search.focused_match]
#foreground = 'CellBackground'
#background = 'CellForeground'
#
#[colors.line_indicator]
#foreground = 'None'
#background = 'None'
#
#[colors.footer_bar]
#foreground = '#5a5a6f'
#background = '#8f8f99'
#
#[colors.selection]
#text       = 'CellBackground'
#background = 'CellForeground'
#
#[colors.normal]
#black   = '#0f1016'
#red     = '#50566c'
#green   = '#b9586a'
#yellow  = '#48847d'
#blue    = '#516ba2'
#magenta = '#5a7ab7'
#cyan    = '#56a397'
#white   = '#8f8f99'
#
#[colors.bright]
#black   = '#5a5a6f'
#red     = '#6B7390'
#green   = '#F7768E'
#yellow  = '#60B1A7'
#blue    = '#6C8FD9'
#magenta = '#79A3F4'
#cyan    = '#73DACA'
#white   = '#c3c3c4'
## END WAL
